# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         No-Giro
version:      0.02
version_from: lib/No/Giro.pm
installdirs:  site
requires:
    PostScript::Simple:            0.06p3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
